### ISSUE TITLE
Ideia de Treinamento

### ISSUE THREAD

**Issue by fabiossantoss** [balivo/intro-xf-2018#1]
Boa tarde balivo , parabéns pelas aulas.
Estou acompanhando e gostaria de sugerir fazer uma aula de como se trabalhar com serviços em background rodando com a aplicação fechada, acessando uma webapi , gravando sqlite etc. Seria muito util, e é um assunto complexo de extrema importancia. Obrigado

**Comment by balivo** [comment]
Olá @fabzon, primeiramente obrigado pelo feedback e fico feliz em saber que estou contribuindo de alguma forma...

Enfim, quanto a parte de serviços (API), este conteúdo será abordado na aula 4 deste treinamento, que será publicada neste final de semana.

O SQLite, é o tema da Aula 3 - Parte 2, junto com injeção de dependência, que será publicado até o final desta semana.

Quanto a serviços em Background, vou produzir algum outro material a respeito e atualizo esta Issue!

Abraço!
