### ISSUE TITLE
Usar models de webapi core .net no xamarin forms

### ISSUE THREAD

**Issue by joaopaulonobrega** [balivo/intro-xf-2018#2]
Olá, primeiramente parabéns pelas video aulas.

Gostaria de saber como usar meus modelos de uma aplicação .net core webapi que usa identity core em um aplicativo xamarin forms, sabendo que tenho que implementar a INotificationPropertyChanged para cada propriedade do meu modelo, e ambos funcionarem.

**Comment by balivo** [comment]
Olá @joaopaulonobrega primeiramente obrigado pelo feedback e fico feliz em saber que ajudei de alguma forma.

Geralmente eu não implemento a lógica de INotifyPropertyChanged em minhas "Models", eu compartilho entre cliente e servidor uma classe apenas com gets e sets para transporte de informações, as chamadas DTOs, em minha humilde opinião, implementar a "mêcanica" da INotifyPropertyChanged do lado do servidor, adianta o "lado" do desenvolvedor, mas faz com que uma lógica desnecessária (avisar a tela que a propriedade foi alterada) seja executada a cada SET, mesmo que não seja mapeado o evento de binding (PropertyChanged obrigatório da interface), ainda há o teste interno para identificar se o evento está nulo (PropertyChanged?.Invoke(.....)).

Espero ter esclarecido sua dúvida.

[]'s
