### ISSUE TITLE
SQLite - Relacionamento entre tabelas

### ISSUE THREAD

**Issue by LeoHacklaender** [balivo/intro-xf-2018#3]
Boa tarde Jefferson,
Gostaria de saber como faço as ligações entre tabelas do tipo One-To-Many, Many-To-Many, se é que tem como. Agradeço desde já a sua ajuda. Abração!!!﻿

**Comment by balivo** [comment]
Oi @LeoHacklaender na realidade a biblioteca "sqlite-net-pcl" usada no treinamento é um "ultra, micro-orm" e vai te ajudar a fazer a parte "mais básica" da coisa, para fazer uma modelagem de entidades desse "porte" eu recomendo vc usar ADO para fazer o acesso a dados e fazer a modelagem "na mão"... Tem vários exemplos de como fazer isso por aí, no próprio https://docs.microsoft.com na parte de Xamairn.Android e Xamarin.iOS vc vai encontrar...

Espero ter ajudado!

[]'s
