### ISSUE TITLE
Dúvida a respeito da Aula 3

### ISSUE THREAD

**Issue by carloshenriquecarniatto** [balivo/intro-xf-2018#4]
Eu não entendi porque foi usado injeção de dependência no projeto, sendo que você consegue fazer tudo diretamente usando um switch e case verificando o sistema operacional e adequando a string de conexão do SQl lite conforme este link do Medium: https://medium.com/@yostane/data-persistence-in-xamarin-using-entity-framework-core-e3a58bdee9d1, uma outra dúvida é como pode ser utilizado o Entity Framework em projetos do Xamarin Forms, principalmente pela questão de Context ou se a Biblioteca do Sqlite já usa este conceito. Desculpa pelas as minhas dúvidas mas é que faz um tempinho que não programo devido a divergências da vida.

**Comment by balivo** [comment]
Oh meu amigo, qq isso! Vamo que vamo...

Atualmente é mais hábito mesmo, pois são 2 soluções igualmente corretas para o mesmo problema... EU, particularmente prefiro não usar o EF Core em aplicativos Xamarin, acho muita coisa... Não se usa uma 12 para matar pombas, se vc acertar, vai acabar tendo carne moída... rs...

Mas se for para pensarmos em argumentos técnicos, podemos ponderar sobre os seguintes aspectos:

-> O "S" do SOLID, acredito que não cabe a classe que consome a conexão com o banco, saber como ela foi inicializada, IMHO é uma lógica separada;

-> Por razões específicas, de acordo com sua necessidade, você pode querer utilizar alguns recursos específicos da inicialização da conexão de cada plataforma, criptografias, senhas, etc... Utilizando a inicialização direto pelo projeto "Core" isso pode ser chato;

-> Você pode querer fazer uma carga inicial a partir de um arquivo de banco de dados pré-existente. Imagine uma situação onde, por algum motivo você precise INICIAR o aplicativo com um volume +/- de dados que seria muito demorado trazer esses dados de uma API... Você pode querer iniciar a partir de um arquivo de banco limpo, e isso é feito diferente em cada plataforma... Dá pra fazer do projeto "Core", sim, mas eu acho "chato";

-> Você pode querer fazer um Backup & Restore do seu arquivo do banco;

Entenda, que muitos dos argumentos apresentados são necessidades específicas de aplicativos, muitas vezes, grandes... Eu prefiro estar preparado (rs)...

Abraço e espero ter esclarecido sua dúvida!
