### ISSUE TITLE
Caractere $.

### ISSUE THREAD

**Issue by domingosafneto** [balivo/intro-xf-2018#5]
Jefferson, o que seria o uso do caractere "$" no seguinte trecho de código, após o GetAsync:
GetAsync($"http://viacep.com.br/ws/{txtCep.Text}/json/"))

Parabéns pelo treinamento, muito bom o vídeo!

Grato pela atenção.

**Comment by balivo** [comment]
Olá @domingosafneto obrigado pelo feedback!

O caractere "$" é o STRING INTERPOLATION, antes escrevíamos algo do tipo:

string.Format("... {0}..", VALOR_QUE_VAI_NO_LUGAR_DO_{0});

Agora podemos usar simplesmente:

$"... {VALOR} ...";

Maiores detalhes em:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated
