### ISSUE TITLE
Diferenças no Visual Studio

### ISSUE THREAD

**Issue by FaustoLuna** [balivo/intro-xf-2018#6]
Primeiramente gostaria de parabenizá-lo pelo excelente trabalho, estou acompanhando e aprendendo muito apesar de ser apenas um entusiasta.
Notei que meu visual studio tem algumas diferenças em comparação com o seu, podia me falar a versão utilizada com as ferramentas utilizadas?

**Comment by balivo** [comment]
Olá amigo, obrigado por acompanhar o conteúdo e espero seguir atendendo às expectativas!

Eu utilizo o Visual Studio 2017 Enterprise e agora estou migrando para o VS2019 (Enterprise, se der)...

Não utilizo nenhuma ferramenta extra (tipo ReSharper, essas merdas ae)... Minha instalação é a mais "seca" possível!
