### ISSUE TITLE
BindingContext

### ISSUE THREAD

**Issue by domingosafneto** [balivo/intro-xf-2018#7]
Introdução Xamarin.Forms (2018) - Aula 2 (1:11:39)
MainPage.xaml.cs

Porque é necessário fazer o convert do parâmetro do "BuscarCep" se o BindingContext com BuscCepViewModel já é instanciado no Construtor?

Grato.

**Comment by balivo** [comment]
Opa amigo, vamos lá...

A propriedade BindingContext é herdada e é do tipo "object"... LOGO para ter acesso aos membros de BuscaCepViewModel faz-se necessário realizar o cast...

[]'s

Balivo.
